<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Post Code_addressPostcode</name>
   <tag></tag>
   <elementGuidId>3b4ada42-d7ba-433d-b925-6bcba13e2df3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressPostcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressPostcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fab51df-8247-4e35-8fe9-c68646e813d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1a424996-8486-4292-938f-f8c10bf0d7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0e8766d3-f629-453e-a466-ce594a5b5356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressPostcode</value>
      <webElementGuid>3bbd9b68-9bc6-418d-ab38-fbe4b23a365d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressPostcode</value>
      <webElementGuid>c91d3ea7-d8eb-4810-9ca4-336ce239d9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6a562fb7-4395-47bc-ba2b-2593f726aab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressPostcode&quot;)</value>
      <webElementGuid>c0e3724f-4ea2-4d02-9d6c-428be0416646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/add new company/frame_input post code</value>
      <webElementGuid>3173a2d7-8171-48a7-b064-2bdefd9de3bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressPostcode']</value>
      <webElementGuid>c7cd739e-5be4-4b1a-a1f7-faed0ae047d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[2]/div[2]/div/div[16]/div[3]/input</value>
      <webElementGuid>30c84c00-f8a6-4937-bd36-33d6335f3b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>476ee999-215f-409f-9db5-93cc49abeb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressPostcode' and @name = 'addressPostcode' and @type = 'text']</value>
      <webElementGuid>8956bd75-e10b-4a5c-b57e-19d97809220a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
