<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TDP_companyTdpNo</name>
   <tag></tag>
   <elementGuidId>9016dc4a-36e9-456e-91fd-7d0dad10511a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='companyTdpNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#companyTdpNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74d483b0-34d6-48e8-a6ed-74141e924c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d562c9a9-0172-48f6-8e0f-e3272e79fca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>04ad17d0-317e-4f47-8bea-ec71ec658f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>companyTdpNo</value>
      <webElementGuid>7a9f232c-c5db-44cb-93bf-f5537a8c29b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyTdpNo</value>
      <webElementGuid>af7128fb-5b07-49d2-90e6-6df561a5be28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5728b17b-7e63-4dce-84df-ee25bd52a7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companyTdpNo&quot;)</value>
      <webElementGuid>47e57600-c826-410d-b1c5-ccab7b6f4367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/add new company/frame_input tdp</value>
      <webElementGuid>872c112a-9587-4440-9846-808293c16f36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='companyTdpNo']</value>
      <webElementGuid>b696ee95-f1ee-4db8-8de3-afa6c23d4e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[2]/div[2]/div/div[10]/div/input</value>
      <webElementGuid>9e81f341-07f2-41c3-9402-d2ae938b031f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>bb85e8d6-dd24-4df8-9025-caa01bd6f8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'companyTdpNo' and @name = 'companyTdpNo' and @type = 'text']</value>
      <webElementGuid>fd20ac7f-5acd-49ec-aa95-2e6734e9a88f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
