<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_English</name>
   <tag></tag>
   <elementGuidId>7778cbb8-040b-4325-9baf-eed629ab3196</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SIvCob > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d6a5ac9-4072-4595-ad48-9ce6d39c65f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/setprefs?sig=0_1JIwcrsLRB21gMyTlbX-Ld_xdas%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwj6pLqGme33AhUIPXAKHZ77AAgQ2ZgBCA0</value>
      <webElementGuid>25805075-8020-4b3c-a83c-7ec8a0e0c50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>f4a29a8a-9035-4bd0-97f2-a7faaaa32fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[1]</value>
      <webElementGuid>193b734f-ec6c-4f79-81e7-af78ec3ff483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a</value>
      <webElementGuid>ac978472-fcd4-4655-aa9c-efc20f43c59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'English')]</value>
      <webElementGuid>301fb191-eff0-41a9-bc1e-48f71c2a7f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/following::a[2]</value>
      <webElementGuid>74c9aac0-9fec-40cd-9130-f4f12d1e85de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basa Bali'])[1]/preceding::a[2]</value>
      <webElementGuid>fa55de3a-aff0-4e5d-9863-332db9eb6a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/preceding::a[3]</value>
      <webElementGuid>eaad3fb9-5592-4eac-83d7-32ab6c159f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='English']/parent::*</value>
      <webElementGuid>cc7b32cf-992b-477e-873c-1b65c6387b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/setprefs?sig=0_1JIwcrsLRB21gMyTlbX-Ld_xdas%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwj6pLqGme33AhUIPXAKHZ77AAgQ2ZgBCA0')]</value>
      <webElementGuid>498b3e3f-5558-47a4-828f-4e20147ee5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>8a2a6a63-1f76-4e71-b865-fb400d0607fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/setprefs?sig=0_1JIwcrsLRB21gMyTlbX-Ld_xdas%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwj6pLqGme33AhUIPXAKHZ77AAgQ2ZgBCA0' and (text() = 'English' or . = 'English')]</value>
      <webElementGuid>17adb774-dd93-4a95-b64f-6c0387d46535</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
