<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot password</name>
   <tag></tag>
   <elementGuidId>937923f7-8408-40bd-a083-34213a8d246d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='forgot']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#forgot</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>740c71d0-49dc-4077-9d92-daa73cba44cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forgot</value>
      <webElementGuid>f4c4eb13-4baa-47dc-bd4e-20abf05850dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>float-lg-right</value>
      <webElementGuid>a7435494-4f9c-47b4-a5b6-7f2d16286d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/merchant-ss-app/forgotpin</value>
      <webElementGuid>5ec0fa8e-41f3-4020-948b-4fb406bc5300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot password ?</value>
      <webElementGuid>db2af2fb-a2da-4caa-9102-87c1bcc86552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgot&quot;)</value>
      <webElementGuid>5a1e85c4-74be-4440-b8ab-bc80ae4a2ef4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='forgot']</value>
      <webElementGuid>7d97337c-dd57-47b3-8fa1-b59067c21a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='remember-me']/div/div[2]/span/a</value>
      <webElementGuid>31b76395-12c0-4b5d-bf9e-711b78928d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot password ?')]</value>
      <webElementGuid>3375b9b2-9083-4a4d-9d92-408812ac351a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2019PT. E2Pay Global UtamaAll rights reserved'])[2]/following::a[1]</value>
      <webElementGuid>f3bda125-1633-4cac-88b0-27c2d48f1262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2019PT. E2Pay Global UtamaAll rights reserved'])[1]/following::a[1]</value>
      <webElementGuid>f763c7ed-e92a-4437-aaae-7ea47f004bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password ?'])[2]/preceding::a[1]</value>
      <webElementGuid>6f6842b7-5fb2-4c81-8d18-22e2c712f0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[2]</value>
      <webElementGuid>4ddffb6a-97f0-4887-aaff-86034d257db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot password ?']/parent::*</value>
      <webElementGuid>28eae772-c872-4b8d-aee4-db2c7d52a467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/merchant-ss-app/forgotpin')]</value>
      <webElementGuid>5361d298-774b-4889-b35b-b84e1f3653a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>a1d18cd1-29c4-4cb8-b88e-4225c6ff1cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'forgot' and @href = '/merchant-ss-app/forgotpin' and (text() = 'Forgot password ?' or . = 'Forgot password ?')]</value>
      <webElementGuid>500a8275-ec3c-42a6-8e0d-58c1d677e65e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
