<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Activity Log</name>
   <tag></tag>
   <elementGuidId>51e403ff-7dfc-45c4-bf8a-386db535b0b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-5001']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-5001 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>469e659f-8380-4ed2-8138-7e7c5c55c0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/merchant-ss-app/en/activityrecord</value>
      <webElementGuid>34ff263d-3e22-4299-b72a-27ca774bcdac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Activity Log</value>
      <webElementGuid>b5d20fea-512e-4f1d-804c-a47fbd4d4fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-5001&quot;)/a[1]</value>
      <webElementGuid>cfb5a420-1f75-4ec0-873f-a6061a36a3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu Slidebar/frame_activity log</value>
      <webElementGuid>657e9099-d504-44c2-a27a-9b7c57f8c6b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-5001']/a</value>
      <webElementGuid>38ed8e09-d795-4355-98f9-83f3cf26dba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Activity Log')]</value>
      <webElementGuid>a985c5b6-4193-4be4-9256-53f70e172729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[1]/following::a[1]</value>
      <webElementGuid>869cecba-0fc0-4fad-93f4-8421113f3213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/merchant-ss-app/en/activityrecord')]</value>
      <webElementGuid>29f0235b-2195-4c16-b602-c0e658f52db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/a</value>
      <webElementGuid>83cafbe1-9a7e-4368-b2f1-e17b83f8f719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/merchant-ss-app/en/activityrecord' and (text() = ' Activity Log' or . = ' Activity Log')]</value>
      <webElementGuid>ef3a311e-1cd4-4d03-aa8f-43db60234fdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
