<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Company List</name>
   <tag></tag>
   <elementGuidId>f27ce847-0064-4e2e-8dbd-536de21eb28f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-2003']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-2003 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70db11de-813e-4243-8a21-40097c5416d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/merchant-ss-app/en/companylist</value>
      <webElementGuid>fb0eabab-ba07-4c76-bc6e-946a87e8d554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Company List</value>
      <webElementGuid>d209ef01-cde1-46d6-813a-cff83faf5e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-2003&quot;)/a[1]</value>
      <webElementGuid>b0f5fca4-57cd-4f55-9cb6-2f9a3ca8dbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu Slidebar/frame_company list</value>
      <webElementGuid>c43d1596-13ff-4dd5-92d0-29fb0b1d26b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-2003']/a</value>
      <webElementGuid>95af67d7-5ffe-4aa2-995f-87c44213363d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Company List')]</value>
      <webElementGuid>c3d8197c-0767-4a51-bf64-e9e64bd6b85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/merchant-ss-app/en/companylist')]</value>
      <webElementGuid>8b83e8e2-99de-4391-b4eb-624c23c2154e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[3]/a</value>
      <webElementGuid>cdd1f579-e68e-4c2f-92a0-bb94b09aa91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/merchant-ss-app/en/companylist' and (text() = ' Company List' or . = ' Company List')]</value>
      <webElementGuid>b576ba05-543d-45e2-8906-07cc8932e4f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
