<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Generate QR Static</name>
   <tag></tag>
   <elementGuidId>4a5f351a-271b-4d92-99e8-881d5c086694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-2006']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-2006 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>97d74e82-0cbb-44a2-b17f-fd6411d2b84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/merchant-ss-app/en/generateqrstatic</value>
      <webElementGuid>f3099d2a-92ea-415a-84cd-94252a961378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Generate QR Static</value>
      <webElementGuid>63939aa6-5999-4897-9e6b-54502b5e9f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-2006&quot;)/a[1]</value>
      <webElementGuid>6c18c6d5-f5f7-4fe2-ab82-8d1fb28b2e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu Slidebar/frame_generate QR</value>
      <webElementGuid>8cca904d-2dec-4aa5-9b28-c300e49b4747</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-2006']/a</value>
      <webElementGuid>ec078c5c-a5fc-4a73-a249-a3881c6e935b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Generate QR Static')]</value>
      <webElementGuid>67bf8b0c-79a5-4133-985e-c50664167dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channels'])[1]/preceding::a[1]</value>
      <webElementGuid>89382369-21c1-4ae0-be7c-94a022b8cc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/merchant-ss-app/en/generateqrstatic')]</value>
      <webElementGuid>374ae412-6da5-4274-9653-1ebd2757a34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[5]/a</value>
      <webElementGuid>8b83597b-9c24-4558-bb47-0e521b3f892b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/merchant-ss-app/en/generateqrstatic' and (text() = ' Generate QR Static' or . = ' Generate QR Static')]</value>
      <webElementGuid>454c3872-1071-4c00-b07a-acde8b08290a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
