<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Merchant List</name>
   <tag></tag>
   <elementGuidId>ef41f581-c8dd-47e9-8939-c889ab76176a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-2004']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-2004 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>58ed2c90-67cb-480f-8e07-2500b34e7a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/merchant-ss-app/en/merchantlist</value>
      <webElementGuid>43a462fa-142d-415a-acce-952fa4a91a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Merchant List</value>
      <webElementGuid>29b6e8c6-a9ff-4872-845d-b00be546b232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-2004&quot;)/a[1]</value>
      <webElementGuid>df30f597-085e-4981-a95b-08cd70545bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu Slidebar/frame_merchant list</value>
      <webElementGuid>bc7dee8b-2a0d-4251-9987-8b0068dc73fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-2004']/a</value>
      <webElementGuid>af25a4d4-8d18-4ca3-929b-8933a4ce9492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Merchant List')]</value>
      <webElementGuid>58b5e5a9-de4b-45c3-810b-f81c48e7ec0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Channels'])[1]/preceding::a[2]</value>
      <webElementGuid>52a79109-27d0-498c-850b-dd22dd40fdd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/merchant-ss-app/en/merchantlist')]</value>
      <webElementGuid>666d8443-542c-438d-b539-e73ba2f9f671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[4]/a</value>
      <webElementGuid>41c5d394-6925-455f-9a96-0f54dc3bcac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/merchant-ss-app/en/merchantlist' and (text() = ' Merchant List' or . = ' Merchant List')]</value>
      <webElementGuid>25705bab-0808-460a-b218-8cf54a65cda6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
