<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Payment Channel Registration Form</name>
   <tag></tag>
   <elementGuidId>d89b81ea-6265-47b6-9a34-ce3ceb30675c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-6004']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-6004 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa9bed53-9be4-47de-9250-174d4a574812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/merchant-ss-app/en/uploadchannelform</value>
      <webElementGuid>2e1e643e-23c2-4619-9333-42f3b6cb6b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Payment Channel Registration Form</value>
      <webElementGuid>2c335b1e-4094-40dd-9320-873a40b83d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-6004&quot;)/a[1]</value>
      <webElementGuid>42f64344-6af3-4a30-86dd-c987edf3e03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu Slidebar/frame_payment channel</value>
      <webElementGuid>88617bc6-94d5-4183-800b-3059a0847f08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-6004']/a</value>
      <webElementGuid>eb515f05-4a64-47ec-a605-250da53d9777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Payment Channel Registration Form')]</value>
      <webElementGuid>a0d5a9cc-c219-4dff-bf97-9ed26ddbcb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::a[1]</value>
      <webElementGuid>dda2ed15-a33d-4cbe-b5dc-e31d6322052f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Merchant'])[1]/preceding::a[1]</value>
      <webElementGuid>049b1b56-54cc-4ef3-b08c-d7c12f74ae17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/merchant-ss-app/en/uploadchannelform')]</value>
      <webElementGuid>b2e66f2c-ca3e-4b0a-bb63-adbb7a118340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[4]/a</value>
      <webElementGuid>83133e36-da60-4793-b381-5bedcd650193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/merchant-ss-app/en/uploadchannelform' and (text() = ' Payment Channel Registration Form' or . = ' Payment Channel Registration Form')]</value>
      <webElementGuid>4f799d53-d8f1-4031-865b-59b0ff999709</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
