<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_pks</name>
   <tag></tag>
   <elementGuidId>86ed8d88-4681-471a-8e7e-d98bbe8330c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='contentframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;contentframe&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>7faeb90f-eb86-4e40-8557-cfb5a0c4054f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>500eb102-c925-4254-9186-1cea153b4896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>db3e16e9-d1dd-44d7-bac2-b6ab3bbee7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0c48287c-4166-427b-b329-f0bab69ca710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>homewelcome</value>
      <webElementGuid>20043fc0-d36a-4d1d-94c3-c37d3973586c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentframe</value>
      <webElementGuid>f0281f57-7cbd-47d2-a0cc-2e999cc74488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[2]</value>
      <webElementGuid>db371a2f-5c11-4b40-99c8-c1cddc1082f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='contentframe']</value>
      <webElementGuid>483ff573-9d26-4ac4-a36d-e5213e75afc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>67ecc9db-ef30-423d-85ce-0027f872f608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'homewelcome' and @name = 'contentframe']</value>
      <webElementGuid>75449567-7529-4b19-aafe-8187dbb397ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
