<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_add new merchant</name>
   <tag></tag>
   <elementGuidId>1969d34e-70be-4df7-b6af-19b1ca4fd1b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='contentframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;contentframe&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>67cc8865-1624-4d31-bc29-7d736abdc7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>18542ac6-5d57-44fe-a37f-e4b11bca559d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>454b2451-bade-470f-95ce-0e33ebb00d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8fd16cc0-1523-4ec9-9b79-bce765c23816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>homewelcome</value>
      <webElementGuid>abc53c3b-e462-4649-a457-2a4ec7e4d8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentframe</value>
      <webElementGuid>fdf68a3b-3da2-4b36-ad4c-6ed40c43f42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[2]</value>
      <webElementGuid>2a1f0251-b6d6-443b-b58b-16d8f8c81d4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='contentframe']</value>
      <webElementGuid>883cfa36-527c-4625-ba00-2e124c4b3285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>d64d0991-7ee6-49bd-8b91-41932dd6dc3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'homewelcome' and @name = 'contentframe']</value>
      <webElementGuid>2734799a-4cec-4b4c-bb2e-9deadec79efb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
