<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_input email notif</name>
   <tag></tag>
   <elementGuidId>b968fe72-82b9-4469-ad0b-1f528787a1d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='contentframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;contentframe&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>28a0a011-c3fc-4677-a7c7-73e1b0ba05b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>356c5904-8c1f-4852-b0b4-a5c9471e93b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2597f47b-a283-4893-8f42-4c234a80b538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>742cbf7a-4406-406a-a94b-00b8c76da31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>homewelcome</value>
      <webElementGuid>b3004748-58ff-4655-9296-bab2e24393c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentframe</value>
      <webElementGuid>93306c8f-0749-477a-add2-1e2c81aa84cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[2]</value>
      <webElementGuid>bbda55d6-636c-40f1-b309-c774a6422e73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='contentframe']</value>
      <webElementGuid>552abd4a-ae79-47c2-b065-68c30a9194cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>c1ad5b23-bf1b-4c19-ac7d-af7f97b2fc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'homewelcome' and @name = 'contentframe']</value>
      <webElementGuid>6532649d-4f23-46ab-9cbe-17fcd0d01523</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
