<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone No_phoneNo</name>
   <tag></tag>
   <elementGuidId>d2c44e2c-5283-48c0-a887-53a1ca4e236a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phoneNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phoneNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56be8ec8-abcd-47a1-ab45-446c9b5f454b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>89ad93e6-4932-48e5-ba03-d467e8bcebdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>5c21ef4d-1a08-4804-a577-877c07a6b4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c01a16fb-69a5-445c-a193-2a79c5d5fc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneNo</value>
      <webElementGuid>c6bf0105-a00c-4cff-b4a1-af96728c57db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNo</value>
      <webElementGuid>850a3eef-d054-4a50-9832-08f8c5f7fb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e4379b4-876f-4326-a04d-fe170dd4630f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneNo&quot;)</value>
      <webElementGuid>0ff6dcaf-7f56-48eb-bee0-9ed1b0f856fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/add new merchant/frame_input no hp admin</value>
      <webElementGuid>8dd9d390-8198-4b38-85b2-c6e0fdb933ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phoneNo']</value>
      <webElementGuid>7b05f865-026d-4e81-87d9-88146037ec97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[2]/div[2]/div/div[22]/div/input</value>
      <webElementGuid>d6c45ba4-2ed9-4ed4-a54b-ecfe01217a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/input</value>
      <webElementGuid>4bd94835-e828-4820-8ab8-67f4492e3a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '62' and @id = 'phoneNo' and @name = 'phoneNo' and @type = 'text']</value>
      <webElementGuid>851f1559-a3d9-40b8-b32b-19ffbccce0d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
