<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Notification URL_notificationUrl</name>
   <tag></tag>
   <elementGuidId>6accb9c7-4657-4e2a-a2a0-c5cdd84681b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notificationUrl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notificationUrl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb9c1cc1-821f-43b9-a5f8-94cb514c137d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ae3e80a0-dd60-4cc9-848f-54585059566b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>format : http://www.domain.com/notificationpages</value>
      <webElementGuid>4ef8cd95-50c2-44de-b332-ca67bc8e2451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>da7d16aa-fe95-431a-98fd-585be5b2ab67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notificationUrl</value>
      <webElementGuid>bedd202e-4808-4e08-a046-246c9574e8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notificationUrl</value>
      <webElementGuid>58663b83-4c3a-4a62-b45c-8f245c25290d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0fa4bb6b-588f-41a4-a850-91222c5dc7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notificationUrl&quot;)</value>
      <webElementGuid>c208d26e-0e0c-4483-981f-52b0f283df04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/add new merchant/frame_input notivication url</value>
      <webElementGuid>4fc9e526-4717-4172-9fd9-1ff80bb4f475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notificationUrl']</value>
      <webElementGuid>b2c82951-0a62-4944-8de2-a027e8d926af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[2]/div[2]/div/div[11]/div/input</value>
      <webElementGuid>c1e3cc18-8dfc-4fd7-a2e0-6efa3f92ce00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/input</value>
      <webElementGuid>e312cd17-b226-4a96-8a7e-e01039870031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'format : http://www.domain.com/notificationpages' and @id = 'notificationUrl' and @name = 'notificationUrl' and @type = 'text']</value>
      <webElementGuid>e830583b-8fa8-400f-bb59-5b1cbca82423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
