<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_np</name>
   <tag></tag>
   <elementGuidId>f7ebbb47-511b-42a5-961b-56118b211941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='np']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#np</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ae414f8-d60e-44e6-bc40-0e65ac1d4330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>********</value>
      <webElementGuid>c0f43097-3c5a-44bd-bfdb-4895669356cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>05d9521c-3d66-4223-8edc-371c5b24194e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>2729b5f0-028f-49e0-9720-0cd5132c935b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>2dda3b80-427c-4e0d-ba85-24a1a8531aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>np</value>
      <webElementGuid>acdd7663-c75e-440b-9af0-2a2a9ff2fc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>np</value>
      <webElementGuid>775182dd-3256-4b80-8bb7-3f937a678981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>64b4c8e9-f019-48db-b1bf-cfc2a5a600e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1c6ad030-7381-41c9-ba53-8cf8322c24cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;np&quot;)</value>
      <webElementGuid>9e59c662-0e35-4008-8908-b2fc610d0b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/add new merchant/frame_input password admin</value>
      <webElementGuid>9b8dd4c4-75d4-43ac-94a5-cdf03d023945</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='np']</value>
      <webElementGuid>1cff89c3-ef33-4970-bbf0-bb3224bcade6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[2]/div[2]/div/div[20]/div/input</value>
      <webElementGuid>09a867e7-dd4f-4dae-92a8-8893e6504e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/input</value>
      <webElementGuid>8b86a25a-331e-42f9-a929-fb150a5fb6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '********' and @name = 'np' and @id = 'np' and @type = 'password']</value>
      <webElementGuid>5d6ff341-dbc9-45e9-a3d0-78846bf5afab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
