<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Callback URL_callbackUrl</name>
   <tag></tag>
   <elementGuidId>36a9af5f-bdf2-406a-8a4a-86149599531b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='callbackUrl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#callbackUrl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7478916e-1e58-4e02-9502-5073a68bc68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cfa27f3b-0d01-4e57-b81e-350d530e02c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>format : http://www.domain.com/callbackpages</value>
      <webElementGuid>b0682109-3a7b-40c8-90f2-a0596aa39a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>82bec386-f1a6-44e1-a5d8-9b19e368914c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>callbackUrl</value>
      <webElementGuid>f7a96ae0-c722-41b1-a4fd-6ed9bfded139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>callbackUrl</value>
      <webElementGuid>645a421c-8b98-49d8-a37b-5d4e377ba9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>697e19f3-afa8-4a40-9f0e-07b9b5c34287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;callbackUrl&quot;)</value>
      <webElementGuid>7bc9547f-5db2-4e32-9a19-c7118af5dc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/add new merchant/frame_input callback url</value>
      <webElementGuid>60aaa922-9461-4f09-92ed-e52756e4f8da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='callbackUrl']</value>
      <webElementGuid>d97a6fc6-b657-4f72-9541-7a1fa04ebd3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[2]/div[2]/div/div[10]/div/input</value>
      <webElementGuid>b10a4587-5b18-47bb-a573-e993cd650472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>5707dd08-1b9f-44a5-8f90-ab3ce88dd7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'format : http://www.domain.com/callbackpages' and @id = 'callbackUrl' and @name = 'callbackUrl' and @type = 'text']</value>
      <webElementGuid>51925c41-3d0d-4908-8d87-cb5ae3973859</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
