<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company_companyName</name>
   <tag></tag>
   <elementGuidId>930e095b-b32a-45cb-8c15-a0a50e8a9772</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='companyName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#companyName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a13218e0-7137-4fd1-bca4-17cf12779bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4f927b6a-3cdf-49c4-93cd-b4314eb62cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-provide</name>
      <type>Main</type>
      <value>typeahead</value>
      <webElementGuid>bdd5b890-262c-4b86-b884-e9d8eb1b5f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>type to search company...</value>
      <webElementGuid>51069f88-2aa5-4c68-87b8-e9b3b389a767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>companyName</value>
      <webElementGuid>6ae1f720-7410-4499-bda5-ca6be8714fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyName</value>
      <webElementGuid>549f71c9-83e8-4cad-849b-1056cefa662e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control typeahead mb-2</value>
      <webElementGuid>2138d6b8-3bfd-4a93-ab80-bfb813b297fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ebb6f77-e1f9-4051-8d2f-959dd7bdaa10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companyName&quot;)</value>
      <webElementGuid>4132ff44-f818-4e69-98f6-77e8d72d9294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/add new merchant/frame_input company</value>
      <webElementGuid>c827073e-821d-4468-995c-be0052fa48a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='companyName']</value>
      <webElementGuid>fa3be56a-e6bb-41c7-825f-3298eb743fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>193480cc-3561-4351-8517-7fcc89b4e706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>58b32a47-b1cf-42fc-98fe-ee556a86efad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'type to search company...' and @id = 'companyName' and @name = 'companyName' and @type = 'text']</value>
      <webElementGuid>a48c3aee-5c97-401f-984b-5a87e70d0aea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
