<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Business Helpdesk Email_helpdeskEmail</name>
   <tag></tag>
   <elementGuidId>7342db11-61cc-468d-934f-6ad6e69b7ebb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='helpdeskEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#helpdeskEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>142c3200-7ff7-4cc7-8e9a-6912223a4f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9095ac77-4c8a-4a22-b1c6-5c91dce14a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>helpdesk email...</value>
      <webElementGuid>040d2ed3-0640-4656-a44d-a208e1568024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>70f06da1-fb37-417c-b9ed-47e6079628d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>helpdeskEmail</value>
      <webElementGuid>ee041f8e-5553-46ef-b4d2-72cf9d991470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>helpdeskEmail</value>
      <webElementGuid>ccb58c5d-0d57-437a-89af-ca5dd8fd29f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7841a14-5e7d-425a-8109-57bb464339fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;helpdeskEmail&quot;)</value>
      <webElementGuid>8a246ab2-da22-4552-830a-de76224f03c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/add new merchant/frame_input helpdesk email</value>
      <webElementGuid>38232d5c-857a-4726-9fdb-685513b7ff63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='helpdeskEmail']</value>
      <webElementGuid>d6cabed1-b447-415d-b038-1446da07a78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[2]/div[2]/div/div[13]/div/input</value>
      <webElementGuid>1993ac2c-1c94-42cd-848b-9bf1a2f6dab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/input</value>
      <webElementGuid>a322e3fe-e47a-4949-8b39-d390d43c10e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'helpdesk email...' and @id = 'helpdeskEmail' and @name = 'helpdeskEmail' and @type = 'text']</value>
      <webElementGuid>d8ace47c-f8d1-4a80-b13a-e569cd9cf0d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
