<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Notification Email_notificationRecipient</name>
   <tag></tag>
   <elementGuidId>97ee9a18-33bd-4f92-809d-032000104e22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notificationRecipient']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#notificationRecipient</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>240929c5-1266-4aa4-b27f-2b5669d31e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5458ee74-ed26-4f21-830c-6fae4beddd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter recipient's email address separated by semi-colon</value>
      <webElementGuid>c14db1de-d978-4ca6-9f37-ad3b187cce66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8dadd030-2c7a-4d9c-ae4f-5568bb08d28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notificationRecipient</value>
      <webElementGuid>ecce049d-46d2-4745-a150-06a7c7f9b9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notificationRecipient</value>
      <webElementGuid>2335cc00-1baa-48ec-a5b0-fe9cb393ab18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d8124ec4-108e-4ed6-8277-d206505820a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notificationRecipient&quot;)</value>
      <webElementGuid>c649dc9b-750f-4b25-be17-205ea351b948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/add new merchant/frame_input email notif</value>
      <webElementGuid>65dd4488-42ec-4452-9506-14ae12af8194</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notificationRecipient']</value>
      <webElementGuid>d84019be-b742-48ba-9c04-4c4bc7498163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[2]/div[2]/div/div[25]/div/input</value>
      <webElementGuid>27af6bf2-c501-4f53-8adf-715904147353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/div/input</value>
      <webElementGuid>a0e1ac92-9b0c-4af6-ab28-29e1cdd0e07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = concat(&quot;Enter recipient&quot; , &quot;'&quot; , &quot;s email address separated by semi-colon&quot;) and @id = 'notificationRecipient' and @name = 'notificationRecipient' and @type = 'text']</value>
      <webElementGuid>1e288b95-7877-4974-add8-996eac588de4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
