<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Request URL_requestUrl</name>
   <tag></tag>
   <elementGuidId>20b14203-5a62-43c9-a8b5-765fa03ecfe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='requestUrl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#requestUrl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>759bf5c4-0134-447e-9a9c-39ef833c4056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>234105a8-d1e3-4961-a3f3-2676404ddf6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>format : http://www.domain.com/requestpages</value>
      <webElementGuid>c8065c1f-d050-4f56-8aa7-878a45d471c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0d21aaf5-1a86-4e5c-9ee6-1f41f1e9dabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>requestUrl</value>
      <webElementGuid>85311e0b-0893-4db2-8186-3cfe1ea39f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>requestUrl</value>
      <webElementGuid>50e6d3eb-3289-46b5-9352-ec063d489119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9802839f-cb35-4b5d-95e8-11791a4bbc21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requestUrl&quot;)</value>
      <webElementGuid>f2543c7a-0fed-45cf-acf0-a47dc7bc1138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/add new merchant/frame_input request url</value>
      <webElementGuid>c8ab9f62-33b5-43c3-86fb-2bc7d6abd4e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='requestUrl']</value>
      <webElementGuid>7ba23293-bdb6-4dd5-b1b9-d8d68d4871c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[2]/div[2]/div/div[9]/div/input</value>
      <webElementGuid>8f7a5223-a583-450a-b1d2-ce3db904e1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>d9c8d2eb-a9a3-4bbd-ae20-98fa23b8227b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'format : http://www.domain.com/requestpages' and @id = 'requestUrl' and @name = 'requestUrl' and @type = 'text']</value>
      <webElementGuid>0aa65a96-5d76-452f-a618-ae97635734a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
